runtime: python27
api_version: 1
threadsafe: false

builtins:
# Deferred is required to use google.appengine.ext.deferred.
- deferred: on

handlers:
- url: /scrape_command
  script: scraper.queue_control.app

- url: /scraper
  script: scraper.worker.app
  login: admin

# MIGRATION ONLY
- url: /data_migration
  script: scraper.data_migration.app
  login: admin

# TEST ONLY
- url: /populate_test_db
  script: scraper.populate_test_db.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: "3.7.3"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'